resource:
  server:
    url: http://localhost:8080
    realm: school-um
    realm-uri: http://localhost:8080/realms/school-um
server:
  port: 8084
  servlet:
    context-path: /api/um

spring:
#  application:
#    name: user-management

  datasource:
    url: jdbc:postgresql://localhost:5432/school-user-management
    username: school-um
    password: school-um
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

  liquibase:
    enabled: false

  kafka:
    producer:
      client-id: um-acc-id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.binark.school.usermanagement.serializer.AccountSerializer
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${resource.server.realm-uri}
          jwk-set-uri: http://localhost:8080/realms/school-um/protocol/openid-connect/certs

      client:
        provider:
          keycloak:
            authorizationUri: http://localhost:8080/school-um/sukulu/protocol/openid-connect/auth
            tokenUri: http://localhost:8080/realms/school-um/protocol/openid-connect/token
            userInfoUri: http://localhost:8080/realms/school-um/protocol/openid-connect/userinfo
            userNameAttribute: preferred_username
            jwkSetUri: http://localhost:8080/realms/school-um/protocol/openid-connect/certs
        #            issuerUri: http://localhost:8080/realms/school-dev
        registration:
          keycloak:
            clientId: sukulu-um
            clientSecret: oQlniOOAUAnhN2WjOeuicIGbxpVnDUcc
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8084/login/oauth2/code/keycloak
            scope:
              - openid

jwt:
  auth:
    converter:
      resource-id: sukulu-um
      principal-attribute: preferred_username


client:
  registration:
    name: keycloak

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

proxy:
  owner:
    url: http://localhost:8081/api/owner
    name: owner

logging:
  level:
    com.binark.school.usermanagement: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
  circuitbreaker:
    enabled: true
    alphanumeric-ids:
      enabled: true

admin:
  key: armelknyobe@gmail.com
  password: password
