scrape_configs:
  - job_name: 'School User Management Module'
    metrics_path: '/admin/monitoring/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:8084']
        labels:
          application: 'User Management'